# Avoid GitHub API authentication when building locally.
github: [metadata]

plugins:
  # - rss
  # - safe_yaml
  # - jekyll-import
  # - import-rss

safe: false

baseurl: https://pglevy.github.io/thats-the-pod/